"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//AUTOGENERATED  by generator.ts
const { jacdac, AccelerometerReg, AccelerometerEvent, REPORT_UPDATE } = require("jacdac-ts");
const maxApi = require("max-api");
exports.Accelerometer = function (service) {
    // get (register to REPORT_UPDATE event to enable background refresh)
    const forcesReg = service.register(AccelerometerReg.Forces);
    forcesReg.on(REPORT_UPDATE, () => {
        const [x, y, z] = forcesReg.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "forces", x.toString(), y.toString(), z.toString()]);
    });
    // get (register to REPORT_UPDATE event to enable background refresh)
    const forcesErrorReg = service.register(AccelerometerReg.ForcesError);
    forcesErrorReg.on(REPORT_UPDATE, () => {
        const [forcesError] = forcesErrorReg.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "forcesError", forcesError.toString()]);
    });
    // get (register to REPORT_UPDATE event to enable background refresh)
    const maxForceReg = service.register(AccelerometerReg.MaxForce);
    const [maxForce] = maxForceReg.unpackedValue;
    // set
    const tiltUpEvent = service.event(AccelerometerEvent.TiltUp);
    tiltUpEvent.on("change", () => {
        // if you need to read the event values
        const values = tiltUpEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "tilt_upEvent", values.toString()]);
    });
    const tiltDownEvent = service.event(AccelerometerEvent.TiltDown);
    tiltDownEvent.on("change", () => {
        // if you need to read the event values
        const values = tiltDownEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "tilt_downEvent", values.toString()]);
    });
    const tiltLeftEvent = service.event(AccelerometerEvent.TiltLeft);
    tiltLeftEvent.on("change", () => {
        // if you need to read the event values
        const values = tiltLeftEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "tilt_leftEvent", values.toString()]);
    });
    const tiltRightEvent = service.event(AccelerometerEvent.TiltRight);
    tiltRightEvent.on("change", () => {
        // if you need to read the event values
        const values = tiltRightEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "tilt_rightEvent", values.toString()]);
    });
    const faceUpEvent = service.event(AccelerometerEvent.FaceUp);
    faceUpEvent.on("change", () => {
        // if you need to read the event values
        const values = faceUpEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "face_upEvent", values.toString()]);
    });
    const faceDownEvent = service.event(AccelerometerEvent.FaceDown);
    faceDownEvent.on("change", () => {
        // if you need to read the event values
        const values = faceDownEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "face_downEvent", values.toString()]);
    });
    const freefallEvent = service.event(AccelerometerEvent.Freefall);
    freefallEvent.on("change", () => {
        // if you need to read the event values
        const values = freefallEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "freefallEvent", values.toString()]);
    });
    const shakeEvent = service.event(AccelerometerEvent.Shake);
    shakeEvent.on("change", () => {
        // if you need to read the event values
        const values = shakeEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "shakeEvent", values.toString()]);
    });
    const force2gEvent = service.event(AccelerometerEvent.Force2g);
    force2gEvent.on("change", () => {
        // if you need to read the event values
        const values = force2gEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "force_2gEvent", values.toString()]);
    });
    const force3gEvent = service.event(AccelerometerEvent.Force3g);
    force3gEvent.on("change", () => {
        // if you need to read the event values
        const values = force3gEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "force_3gEvent", values.toString()]);
    });
    const force6gEvent = service.event(AccelerometerEvent.Force6g);
    force6gEvent.on("change", () => {
        // if you need to read the event values
        const values = force6gEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "force_6gEvent", values.toString()]);
    });
    const force8gEvent = service.event(AccelerometerEvent.Force8g);
    force8gEvent.on("change", () => {
        // if you need to read the event values
        const values = force8gEvent.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "force_8gEvent", values.toString()]);
    });
};
