"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//AUTOGENERATED  by generator.ts
const { jacdac, FlexReg, FlexEvent, REPORT_UPDATE } = require("jacdac-ts");
const maxApi = require("max-api");
exports.Flex = function (service) {
    // get (register to REPORT_UPDATE event to enable background refresh)
    const bendingReg = service.register(FlexReg.Bending);
    bendingReg.on(REPORT_UPDATE, () => {
        const [bending] = bendingReg.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "bending", bending.toString()]);
    });
};
