"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//AUTOGENERATED  by generator.ts
const { jacdac, TvocReg, TvocEvent, REPORT_UPDATE } = require("jacdac-ts");
const maxApi = require("max-api");
exports.Tvoc = function (service) {
    // get (register to REPORT_UPDATE event to enable background refresh)
    const tVOCReg = service.register(TvocReg.TVOC);
    tVOCReg.on(REPORT_UPDATE, () => {
        const [tVOC] = tVOCReg.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "tVOC", tVOC.toString()]);
    });
    // get (register to REPORT_UPDATE event to enable background refresh)
    const tVOCErrorReg = service.register(TvocReg.TVOCError);
    tVOCErrorReg.on(REPORT_UPDATE, () => {
        const [tVOCError] = tVOCErrorReg.unpackedValue;
        maxApi.outlet([service.maxID.toString(), "tVOCError", tVOCError.toString()]);
    });
};
