        
        //AUTOGENERATED  by generator.ts
        const {jacdac, BarometerReg, BarometerEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Barometer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const pressureReg = service.register(BarometerReg.Pressure)
pressureReg.on(REPORT_UPDATE, () => {

    
const [pressure] : [number] = pressureReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressure", pressure.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const pressureErrorReg = service.register(BarometerReg.PressureError)
pressureErrorReg.on(REPORT_UPDATE, () => {

    
const [pressureError] : [number] = pressureErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressureError", pressureError.toString()])

})


}

 export {};