        
        //AUTOGENERATED  by generator.ts
        const {jacdac, ButtonReg, ButtonEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Button = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const pressureReg = service.register(ButtonReg.Pressure)
pressureReg.on(REPORT_UPDATE, () => {

    
const [pressure] : [number] = pressureReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressure", pressure.toString()])

})




// get (register to REPORT_UPDATE event to enable background refresh)
const pressedReg = service.register(ButtonReg.Pressed)
pressedReg.on(REPORT_UPDATE, () => {

    
const [pressed] : [number] = pressedReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressed", pressed.toString()])

})


const downEvent = service.event(ButtonEvent.Down)
downEvent.on("change", () => {
    // if you need to read the event values
     const values = downEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_down", values.toString()])

})


const upEvent = service.event(ButtonEvent.Up)
upEvent.on("change", () => {
    // if you need to read the event values
     const values = upEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_up", values.toString()])

})


const holdEvent = service.event(ButtonEvent.Hold)
holdEvent.on("change", () => {
    // if you need to read the event values
     const values = holdEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_hold", values.toString()])

})


}

 export {};