        
        //AUTOGENERATED  by generator.ts
        const {jacdac, CompassReg, CompassEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Compass = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const headingReg = service.register(CompassReg.Heading)
headingReg.on(REPORT_UPDATE, () => {

    
const [heading] : [number] = headingReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "heading", heading.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(CompassReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const headingErrorReg = service.register(CompassReg.HeadingError)
headingErrorReg.on(REPORT_UPDATE, () => {

    
const [headingError] : [number] = headingErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "headingError", headingError.toString()])

})



}

 export {};