        
        //AUTOGENERATED  by generator.ts
        const {jacdac, GamepadReg, GamepadEvent, GamepadButtons, REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Gamepad = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const directionReg = service.register(GamepadReg.Direction)
directionReg.on(REPORT_UPDATE, () => {

    
const [buttons, x, y] : [typeof GamepadButtons, number, number] = directionReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "direction", buttons.toString(),x.toString(),y.toString()])

})






const buttonsChangedEvent = service.event(GamepadEvent.ButtonsChanged)
buttonsChangedEvent.on("change", () => {
    // if you need to read the event values
     const values = buttonsChangedEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_buttonsChanged", values.toString()])

})


}

 export {};