        
        //AUTOGENERATED  by generator.ts
        const {jacdac, GyroscopeReg, GyroscopeEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Gyroscope = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const rotationRatesReg = service.register(GyroscopeReg.RotationRates)
rotationRatesReg.on(REPORT_UPDATE, () => {

    
const [x, y, z] : [number, number, number] = rotationRatesReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "rotationRates", x.toString(),y.toString(),z.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const rotationRatesErrorReg = service.register(GyroscopeReg.RotationRatesError)
rotationRatesErrorReg.on(REPORT_UPDATE, () => {

    
const [rotationRatesError] : [number] = rotationRatesErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "rotationRatesError", rotationRatesError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const maxRateReg = service.register(GyroscopeReg.MaxRate)
const [maxRate] : [number] = maxRateReg.unpackedValue
// set



}

 export {};