        
        //AUTOGENERATED  by generator.ts
        const {jacdac, SoundLevelReg, SoundLevelEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.SoundLevel = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const soundLevelReg = service.register(SoundLevelReg.SoundLevel)
soundLevelReg.on(REPORT_UPDATE, () => {

    
const [soundLevel] : [number] = soundLevelReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "soundLevel", soundLevel.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(SoundLevelReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const loudThresholdReg = service.register(SoundLevelReg.LoudThreshold)
const [loudThreshold] : [number] = loudThresholdReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const quietThresholdReg = service.register(SoundLevelReg.QuietThreshold)
const [quietThreshold] : [number] = quietThresholdReg.unpackedValue
// set

const loudEvent = service.event(SoundLevelEvent.Loud)
loudEvent.on("change", () => {
    // if you need to read the event values
     const values = loudEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_loud", values.toString()])

})


const quietEvent = service.event(SoundLevelEvent.Quiet)
quietEvent.on("change", () => {
    // if you need to read the event values
     const values = quietEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_quiet", values.toString()])

})


}

 export {};