        
        //AUTOGENERATED  by generator.ts
        const {jacdac, SoundSpectrumReg, SoundSpectrumEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.SoundSpectrum = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const frequencyBinsReg = service.register(SoundSpectrumReg.FrequencyBins)
frequencyBinsReg.on(REPORT_UPDATE, () => {

    
const [frequencyBins] : [Buffer] = frequencyBinsReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "frequencyBins", frequencyBins.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(SoundSpectrumReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const fftPow2SizeReg = service.register(SoundSpectrumReg.FftPow2Size)
const [fftPow2Size] : [number] = fftPow2SizeReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const minDecibelsReg = service.register(SoundSpectrumReg.MinDecibels)
const [minDecibels] : [number] = minDecibelsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxDecibelsReg = service.register(SoundSpectrumReg.MaxDecibels)
const [maxDecibels] : [number] = maxDecibelsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const smoothingTimeConstantReg = service.register(SoundSpectrumReg.SmoothingTimeConstant)
const [smoothingTimeConstant] : [number] = smoothingTimeConstantReg.unpackedValue
// set

}

 export {};