        
        //AUTOGENERATED  by generator.ts
        const {jacdac, SwitchReg, SwitchEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Switch = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const activeReg = service.register(SwitchReg.Active)
activeReg.on(REPORT_UPDATE, () => {

    
const [active] : [number] = activeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "active", active.toString()])

})






const onEvent = service.event(SwitchEvent.On)
onEvent.on("change", () => {
    // if you need to read the event values
     const values = onEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_on", values.toString()])

})


const offEvent = service.event(SwitchEvent.Off)
offEvent.on("change", () => {
    // if you need to read the event values
     const values = offEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_off", values.toString()])

})


}

 export {};