        
        //AUTOGENERATED  by generator.ts
        const {jacdac, TemperatureReg, TemperatureEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Temperature = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const temperatureReg = service.register(TemperatureReg.Temperature)
temperatureReg.on(REPORT_UPDATE, () => {

    
const [temperature] : [number] = temperatureReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "temperature", temperature.toString()])

})






// get (register to REPORT_UPDATE event to enable background refresh)
const temperatureErrorReg = service.register(TemperatureReg.TemperatureError)
temperatureErrorReg.on(REPORT_UPDATE, () => {

    
const [temperatureError] : [number] = temperatureErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "temperatureError", temperatureError.toString()])

})




}

 export {};