{
"accelerometer" : "JDServiceAccelerometer,"
"arcade gamepad" : "JDServiceArcadeGamepad,"
"barometer" : "JDServiceBarometer,"
"button" : "JDServiceButton,"
"color" : "JDServiceColor,"
"compass" : "JDServiceCompass,"
"distance" : "JDServiceDistance,"
"equivalent co₂" : "JDServiceECO2,"
"flex" : "JDServiceFlex,"
"gamepad" : "JDServiceGamepad,"
"gyroscope" : "JDServiceGyroscope,"
"heart rate" : "JDServiceHeartRate,"
"humidity" : "JDServiceHumidity,"
"illuminance" : "JDServiceIlluminance,"
"light level" : "JDServiceLightLevel,"
"magnetometer" : "JDServiceMagnetometer,"
"matrix keypad" : "JDServiceMatrixKeypad,"
"motion" : "JDServiceMotion,"
"potentiometer" : "JDServicePotentiometer,"
"pulse oximeter" : "JDServicePulseOximeter,"
"rain gauge" : "JDServiceRainGauge,"
"real time clock" : "JDServiceRealTimeClock,"
"reflected light" : "JDServiceReflectedLight,"
"rotary encoder" : "JDServiceRotaryEncoder,"
"rover" : "JDServiceRover,"
"soil moisture" : "JDServiceSoilMoisture,"
"sound level" : "JDServiceSoundLevel,"
"sound spectrum" : "JDServiceSoundSpectrum,"
"switch" : "JDServiceSwitch,"
"temperature" : "JDServiceTemperature,"
"total volatile organic compound" : "JDServiceTvoc,"
"uv index" : "JDServiceUvIndex,"
"water level" : "JDServiceWaterLevel,"
"weight scale" : "JDServiceWeightScale,"
"wind direction" : "JDServiceWindDirection,"
"wind speed" : "JDServiceWindSpeed"
}