        
//AUTOGENERATED  by generator.ts
const {jacdac, SevenSegmentDisplayReg, SevenSegmentDisplayEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.SevenSegmentDisplay = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const digitsReg = service.register(SevenSegmentDisplayReg.Digits)
const [digits] : [Buffer] = digitsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(SevenSegmentDisplayReg.Brightness)
const [brightness] : [number] = brightnessReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const doubleDotsReg = service.register(SevenSegmentDisplayReg.DoubleDots)
const [doubleDots] : [number] = doubleDotsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const digitCountReg = service.register(SevenSegmentDisplayReg.DigitCount)
const [digitCount] : [number] = digitCountReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const decimalPointReg = service.register(SevenSegmentDisplayReg.DecimalPoint)
const [decimalPoint] : [number] = decimalPointReg.unpackedValue



}

 export {};