        
//AUTOGENERATED  by generator.ts
const {jacdac, AccelerometerReg, AccelerometerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Accelerometer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const forcesReg = service.register(AccelerometerReg.Forces)
forcesReg.on(REPORT_UPDATE, () => {

    
const [x, y, z] : [number, number, number] = forcesReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "forces", x.toString(),y.toString(),z.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const forcesErrorReg = service.register(AccelerometerReg.ForcesError)
forcesErrorReg.on(REPORT_UPDATE, () => {

    
const [forcesError] : [number] = forcesErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "forcesError", forcesError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const maxForceReg = service.register(AccelerometerReg.MaxForce)
const [maxForce] : [number] = maxForceReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxForcesSupportedReg = service.register(AccelerometerReg.MaxForcesSupported)
const [maxForcesSupported] : [number[]] = maxForcesSupportedReg.unpackedValue

























}

 export {};