        
        //AUTOGENERATED  by generator.ts
        const {jacdac, AccelerometerReg, AccelerometerEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Accelerometer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const forcesReg = service.register(AccelerometerReg.Forces)
forcesReg.on(REPORT_UPDATE, () => {

    
const [x, y, z] : [number, number, number] = forcesReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "forces", x.toString(),y.toString(),z.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const forcesErrorReg = service.register(AccelerometerReg.ForcesError)
forcesErrorReg.on(REPORT_UPDATE, () => {

    
const [forcesError] : [number] = forcesErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "forcesError", forcesError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const maxForceReg = service.register(AccelerometerReg.MaxForce)
const [maxForce] : [number] = maxForceReg.unpackedValue
// set



const tiltUpEvent = service.event(AccelerometerEvent.TiltUp)
tiltUpEvent.on("change", () => {
    // if you need to read the event values
     const values = tiltUpEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_tiltUp", values.toString()])

})


const tiltDownEvent = service.event(AccelerometerEvent.TiltDown)
tiltDownEvent.on("change", () => {
    // if you need to read the event values
     const values = tiltDownEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_tiltDown", values.toString()])

})


const tiltLeftEvent = service.event(AccelerometerEvent.TiltLeft)
tiltLeftEvent.on("change", () => {
    // if you need to read the event values
     const values = tiltLeftEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_tiltLeft", values.toString()])

})


const tiltRightEvent = service.event(AccelerometerEvent.TiltRight)
tiltRightEvent.on("change", () => {
    // if you need to read the event values
     const values = tiltRightEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_tiltRight", values.toString()])

})


const faceUpEvent = service.event(AccelerometerEvent.FaceUp)
faceUpEvent.on("change", () => {
    // if you need to read the event values
     const values = faceUpEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_faceUp", values.toString()])

})


const faceDownEvent = service.event(AccelerometerEvent.FaceDown)
faceDownEvent.on("change", () => {
    // if you need to read the event values
     const values = faceDownEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_faceDown", values.toString()])

})


const freefallEvent = service.event(AccelerometerEvent.Freefall)
freefallEvent.on("change", () => {
    // if you need to read the event values
     const values = freefallEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_freefall", values.toString()])

})


const shakeEvent = service.event(AccelerometerEvent.Shake)
shakeEvent.on("change", () => {
    // if you need to read the event values
     const values = shakeEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_shake", values.toString()])

})


const force2gEvent = service.event(AccelerometerEvent.Force2g)
force2gEvent.on("change", () => {
    // if you need to read the event values
     const values = force2gEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_force2g", values.toString()])

})


const force3gEvent = service.event(AccelerometerEvent.Force3g)
force3gEvent.on("change", () => {
    // if you need to read the event values
     const values = force3gEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_force3g", values.toString()])

})


const force6gEvent = service.event(AccelerometerEvent.Force6g)
force6gEvent.on("change", () => {
    // if you need to read the event values
     const values = force6gEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_force6g", values.toString()])

})


const force8gEvent = service.event(AccelerometerEvent.Force8g)
force8gEvent.on("change", () => {
    // if you need to read the event values
     const values = force8gEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_force8g", values.toString()])

})


}

 export {};