        
//AUTOGENERATED  by generator.ts
const {jacdac, ArcadeGamepadReg, ArcadeGamepadEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.ArcadeGamepad = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const buttonsReg = service.register(ArcadeGamepadReg.Buttons)
buttonsReg.on(REPORT_UPDATE, () => {

    
const [rest] : [([jacdac.ArcadeGamepadButton, number])[]] = buttonsReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "buttons", rest.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const availableButtonsReg = service.register(ArcadeGamepadReg.AvailableButtons)
const [button] : [jacdac.ArcadeGamepadButton[]] = availableButtonsReg.unpackedValue





}

 export {};