        
//AUTOGENERATED  by generator.ts
const {jacdac, ArcadeSoundReg, ArcadeSoundEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.ArcadeSound = function(service){

// get (register to REPORT_UPDATE event to enable background refresh)
const sampleRateReg = service.register(ArcadeSoundReg.SampleRate)
const [sampleRate] : [number] = sampleRateReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const bufferSizeReg = service.register(ArcadeSoundReg.BufferSize)
const [bufferSize] : [number] = bufferSizeReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const bufferPendingReg = service.register(ArcadeSoundReg.BufferPending)
bufferPendingReg.on(REPORT_UPDATE, () => {

    
const [bufferPending] : [number] = bufferPendingReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "bufferPending", bufferPending.toString()])

})


}

 export {};