        
//AUTOGENERATED  by generator.ts
const {jacdac, BarcodeReaderReg, BarcodeReaderEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.BarcodeReader = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(BarcodeReaderReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const formatsReg = service.register(BarcodeReaderReg.Formats)
const [format] : [jacdac.BarcodeReaderFormat[]] = formatsReg.unpackedValue



}

 export {};