        
//AUTOGENERATED  by generator.ts
const {jacdac, BaseReg, BaseEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Base = function(service){


// get (register to REPORT_UPDATE event to enable background refresh)
const instanceNameReg = service.register(BaseReg.InstanceName)
const [instanceName] : [string] = instanceNameReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const statusCodeReg = service.register(BaseReg.StatusCode)
statusCodeReg.on(REPORT_UPDATE, () => {

    
const [code, vendorCode] : [number, number] = statusCodeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "statusCode", code.toString(),vendorCode.toString()])

})




}

 export {};