        
//AUTOGENERATED  by generator.ts
const {jacdac, BitRadioReg, BitRadioEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.BitRadio = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(BitRadioReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const groupReg = service.register(BitRadioReg.Group)
const [group] : [number] = groupReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const transmissionPowerReg = service.register(BitRadioReg.TransmissionPower)
const [transmissionPower] : [number] = transmissionPowerReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const frequencyBandReg = service.register(BitRadioReg.FrequencyBand)
const [frequencyBand] : [number] = frequencyBandReg.unpackedValue
// set











}

 export {};