        
//AUTOGENERATED  by generator.ts
const {jacdac, BootloaderReg, BootloaderEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Bootloader = function(service){









}

 export {};