        
//AUTOGENERATED  by generator.ts
const {jacdac, BrailleDisplayReg, BrailleDisplayEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.BrailleDisplay = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(BrailleDisplayReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const patternsReg = service.register(BrailleDisplayReg.Patterns)
const [patterns] : [string] = patternsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const lengthReg = service.register(BrailleDisplayReg.Length)
const [length] : [number] = lengthReg.unpackedValue

}

 export {};