        
//AUTOGENERATED  by generator.ts
const {jacdac, BridgeReg, BridgeEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Bridge = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(BridgeReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

}

 export {};