        
//AUTOGENERATED  by generator.ts
const {jacdac, ButtonReg, ButtonEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Button = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const pressureReg = service.register(ButtonReg.Pressure)
pressureReg.on(REPORT_UPDATE, () => {

    
const [pressure] : [number] = pressureReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressure", pressure.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const analogReg = service.register(ButtonReg.Analog)
const [analog] : [number] = analogReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const pressedReg = service.register(ButtonReg.Pressed)
pressedReg.on(REPORT_UPDATE, () => {

    
const [pressed] : [number] = pressedReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressed", pressed.toString()])

})








}

 export {};