        
//AUTOGENERATED  by generator.ts
const {jacdac, BuzzerReg, BuzzerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Buzzer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const volumeReg = service.register(BuzzerReg.Volume)
const [volume] : [number] = volumeReg.unpackedValue
// set



}

 export {};