        
//AUTOGENERATED  by generator.ts
const {jacdac, CapacitiveButtonReg, CapacitiveButtonEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.CapacitiveButton = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const thresholdReg = service.register(CapacitiveButtonReg.Threshold)
const [threshold] : [number] = thresholdReg.unpackedValue
// set




}

 export {};