        
//AUTOGENERATED  by generator.ts
const {jacdac, CharacterScreenReg, CharacterScreenEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.CharacterScreen = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const messageReg = service.register(CharacterScreenReg.Message)
const [message] : [string] = messageReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(CharacterScreenReg.Brightness)
const [brightness] : [number] = brightnessReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(CharacterScreenReg.Variant)
const [variant] : [jacdac.CharacterScreenVariant] = variantReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const textDirectionReg = service.register(CharacterScreenReg.TextDirection)
const [textDirection] : [jacdac.CharacterScreenTextDirection] = textDirectionReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const rowsReg = service.register(CharacterScreenReg.Rows)
const [rows] : [number] = rowsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const columnsReg = service.register(CharacterScreenReg.Columns)
const [columns] : [number] = columnsReg.unpackedValue

}

 export {};