        
//AUTOGENERATED  by generator.ts
const {jacdac, CodalMessageBusReg, CodalMessageBusEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.CodalMessageBus = function(service){



}

 export {};