        
//AUTOGENERATED  by generator.ts
const {jacdac, ColorReg, ColorEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Color = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const colorReg = service.register(ColorReg.Color)
colorReg.on(REPORT_UPDATE, () => {

    
const [red, green, blue] : [number, number, number] = colorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "color", red.toString(),green.toString(),blue.toString()])

})


}

 export {};