        
//AUTOGENERATED  by generator.ts
const {jacdac, SystemReg, SystemEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.System = function(service){














// get (register to REPORT_UPDATE event to enable background refresh)
const intensityReg = service.register(SystemReg.Intensity)
const [intensity] : [number] = intensityReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const valueReg = service.register(SystemReg.Value)
const [value] : [number] = valueReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const minValueReg = service.register(SystemReg.MinValue)
const [minValue] : [number] = minValueReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxValueReg = service.register(SystemReg.MaxValue)
const [maxValue] : [number] = maxValueReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxPowerReg = service.register(SystemReg.MaxPower)
const [maxPower] : [number] = maxPowerReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const streamingSamplesReg = service.register(SystemReg.StreamingSamples)
const [streamingSamples] : [number] = streamingSamplesReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const streamingIntervalReg = service.register(SystemReg.StreamingInterval)
const [streamingInterval] : [number] = streamingIntervalReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const readingReg = service.register(SystemReg.Reading)
readingReg.on(REPORT_UPDATE, () => {

    
const [reading] : [number] = readingReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "reading", reading.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const readingRangeReg = service.register(SystemReg.ReadingRange)
const [readingRange] : [number] = readingRangeReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const supportedRangesReg = service.register(SystemReg.SupportedRanges)
const [range] : [number[]] = supportedRangesReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const minReadingReg = service.register(SystemReg.MinReading)
const [minReading] : [number] = minReadingReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxReadingReg = service.register(SystemReg.MaxReading)
const [maxReading] : [number] = maxReadingReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const readingErrorReg = service.register(SystemReg.ReadingError)
readingErrorReg.on(REPORT_UPDATE, () => {

    
const [readingError] : [number] = readingErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "readingError", readingError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const readingResolutionReg = service.register(SystemReg.ReadingResolution)
const [readingResolution] : [number] = readingResolutionReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const inactiveThresholdReg = service.register(SystemReg.InactiveThreshold)
const [inactiveThreshold] : [number] = inactiveThresholdReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const activeThresholdReg = service.register(SystemReg.ActiveThreshold)
const [activeThreshold] : [number] = activeThresholdReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const streamingPreferredIntervalReg = service.register(SystemReg.StreamingPreferredInterval)
const [streamingPreferredInterval] : [number] = streamingPreferredIntervalReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(SystemReg.Variant)
const [variant] : [number] = variantReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const statusCodeReg = service.register(SystemReg.StatusCode)
statusCodeReg.on(REPORT_UPDATE, () => {

    
const [code, vendorCode] : [jacdac.SystemStatusCodes, number] = statusCodeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "statusCode", code.toString(),vendorCode.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const instanceNameReg = service.register(SystemReg.InstanceName)
const [instanceName] : [string] = instanceNameReg.unpackedValue











}

 export {};