        
//AUTOGENERATED  by generator.ts
const {jacdac, ControlReg, ControlEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Control = function(service){
















// get (register to REPORT_UPDATE event to enable background refresh)
const resetInReg = service.register(ControlReg.ResetIn)
const [resetIn] : [number] = resetInReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const deviceDescriptionReg = service.register(ControlReg.DeviceDescription)
const [deviceDescription] : [string] = deviceDescriptionReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const productIdentifierReg = service.register(ControlReg.ProductIdentifier)
const [productIdentifier] : [number] = productIdentifierReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const bootloaderProductIdentifierReg = service.register(ControlReg.BootloaderProductIdentifier)
const [bootloaderProductIdentifier] : [number] = bootloaderProductIdentifierReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const firmwareVersionReg = service.register(ControlReg.FirmwareVersion)
const [firmwareVersion] : [string] = firmwareVersionReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const mcuTemperatureReg = service.register(ControlReg.McuTemperature)
mcuTemperatureReg.on(REPORT_UPDATE, () => {

    
const [mcuTemperature] : [number] = mcuTemperatureReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "mcuTemperature", mcuTemperature.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const uptimeReg = service.register(ControlReg.Uptime)
uptimeReg.on(REPORT_UPDATE, () => {

    
const [uptime] : [number] = uptimeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "uptime", uptime.toString()])

})


}

 export {};