        
//AUTOGENERATED  by generator.ts
const {jacdac, DashboardReg, DashboardEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Dashboard = function(service){


}

 export {};