        
//AUTOGENERATED  by generator.ts
const {jacdac, DistanceReg, DistanceEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Distance = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const distanceReg = service.register(DistanceReg.Distance)
distanceReg.on(REPORT_UPDATE, () => {

    
const [distance] : [number] = distanceReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "distance", distance.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const distanceErrorReg = service.register(DistanceReg.DistanceError)
distanceErrorReg.on(REPORT_UPDATE, () => {

    
const [distanceError] : [number] = distanceErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "distanceError", distanceError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const minRangeReg = service.register(DistanceReg.MinRange)
const [minRange] : [number] = minRangeReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxRangeReg = service.register(DistanceReg.MaxRange)
const [maxRange] : [number] = maxRangeReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(DistanceReg.Variant)
const [variant] : [jacdac.DistanceVariant] = variantReg.unpackedValue

}

 export {};