        
//AUTOGENERATED  by generator.ts
const {jacdac, DmxReg, DmxEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Dmx = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(DmxReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set


}

 export {};