        
//AUTOGENERATED  by generator.ts
const {jacdac, DotMatrixReg, DotMatrixEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.DotMatrix = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const dotsReg = service.register(DotMatrixReg.Dots)
const [dots] : [Buffer] = dotsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(DotMatrixReg.Brightness)
const [brightness] : [number] = brightnessReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const rowsReg = service.register(DotMatrixReg.Rows)
const [rows] : [number] = rowsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const columnsReg = service.register(DotMatrixReg.Columns)
const [columns] : [number] = columnsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(DotMatrixReg.Variant)
const [variant] : [jacdac.DotMatrixVariant] = variantReg.unpackedValue

}

 export {};