        
        //AUTOGENERATED  by generator.ts
        const {jacdac, ECO2Reg, ECO2Event,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.ECO2 = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const eCO2Reg = service.register(ECO2Reg.ECO2)
eCO2Reg.on(REPORT_UPDATE, () => {

    
const [eCO2] : [number] = eCO2Reg.unpackedValue
maxApi.outlet([service.maxID.toString(), "eCO2", eCO2.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const eCO2ErrorReg = service.register(ECO2Reg.ECO2Error)
eCO2ErrorReg.on(REPORT_UPDATE, () => {

    
const [eCO2Error] : [number] = eCO2ErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "eCO2Error", eCO2Error.toString()])

})








}

 export {};