        
//AUTOGENERATED  by generator.ts
const {jacdac, GamepadReg, GamepadEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Gamepad = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const directionReg = service.register(GamepadReg.Direction)
directionReg.on(REPORT_UPDATE, () => {

    
const [buttons, x, y] : [jacdac.GamepadButtons, number, number] = directionReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "direction", buttons.toString(),x.toString(),y.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(GamepadReg.Variant)
const [variant] : [jacdac.GamepadVariant] = variantReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const buttonsAvailableReg = service.register(GamepadReg.ButtonsAvailable)
const [buttonsAvailable] : [jacdac.GamepadButtons] = buttonsAvailableReg.unpackedValue



}

 export {};