        
//AUTOGENERATED  by generator.ts
const {jacdac, HeartRateReg, HeartRateEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.HeartRate = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const heartRateReg = service.register(HeartRateReg.HeartRate)
heartRateReg.on(REPORT_UPDATE, () => {

    
const [heartRate] : [number] = heartRateReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "heartRate", heartRate.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const heartRateErrorReg = service.register(HeartRateReg.HeartRateError)
heartRateErrorReg.on(REPORT_UPDATE, () => {

    
const [heartRateError] : [number] = heartRateErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "heartRateError", heartRateError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(HeartRateReg.Variant)
const [variant] : [jacdac.HeartRateVariant] = variantReg.unpackedValue

}

 export {};