        
//AUTOGENERATED  by generator.ts
const {jacdac, HidMouseReg, HidMouseEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.HidMouse = function(service){



}

 export {};