        
//AUTOGENERATED  by generator.ts
const {jacdac, HidKeyboardReg, HidKeyboardEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.HidKeyboard = function(service){
const [selector, modifiers, action] = rest[0]


}

 export {};