        
//AUTOGENERATED  by generator.ts
const {jacdac, HumidityReg, HumidityEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Humidity = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const humidityReg = service.register(HumidityReg.Humidity)
humidityReg.on(REPORT_UPDATE, () => {

    
const [humidity] : [number] = humidityReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "humidity", humidity.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const humidityErrorReg = service.register(HumidityReg.HumidityError)
humidityErrorReg.on(REPORT_UPDATE, () => {

    
const [humidityError] : [number] = humidityErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "humidityError", humidityError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const minHumidityReg = service.register(HumidityReg.MinHumidity)
const [minHumidity] : [number] = minHumidityReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxHumidityReg = service.register(HumidityReg.MaxHumidity)
const [maxHumidity] : [number] = maxHumidityReg.unpackedValue

}

 export {};