        
        //AUTOGENERATED  by generator.ts
        const {jacdac, IlluminanceReg, IlluminanceEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Illuminance = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const illuminanceReg = service.register(IlluminanceReg.Illuminance)
illuminanceReg.on(REPORT_UPDATE, () => {

    
const [illuminance] : [number] = illuminanceReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "illuminance", illuminance.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const illuminanceErrorReg = service.register(IlluminanceReg.IlluminanceError)
illuminanceErrorReg.on(REPORT_UPDATE, () => {

    
const [illuminanceError] : [number] = illuminanceErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "illuminanceError", illuminanceError.toString()])

})


}

 export {};