        
//AUTOGENERATED  by generator.ts
const {jacdac, IndexedScreenReg, IndexedScreenEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.IndexedScreen = function(service){


// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(IndexedScreenReg.Brightness)
const [brightness] : [number] = brightnessReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const paletteReg = service.register(IndexedScreenReg.Palette)
const [rest] : [([number, number, number])[]] = paletteReg.unpackedValue
// set
const [blue, green, red] = rest[0]

// get (register to REPORT_UPDATE event to enable background refresh)
const bitsPerPixelReg = service.register(IndexedScreenReg.BitsPerPixel)
const [bitsPerPixel] : [number] = bitsPerPixelReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const widthReg = service.register(IndexedScreenReg.Width)
const [width] : [number] = widthReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const heightReg = service.register(IndexedScreenReg.Height)
const [height] : [number] = heightReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const widthMajorReg = service.register(IndexedScreenReg.WidthMajor)
const [widthMajor] : [number] = widthMajorReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const upSamplingReg = service.register(IndexedScreenReg.UpSampling)
const [upSampling] : [number] = upSamplingReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const rotationReg = service.register(IndexedScreenReg.Rotation)
const [rotation] : [number] = rotationReg.unpackedValue
// set

}

 export {};