        
//AUTOGENERATED  by generator.ts
const {jacdac, InfrastructureReg, InfrastructureEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Infrastructure = function(service){


}

 export {};