        
//AUTOGENERATED  by generator.ts
const {jacdac, LedPixelReg, LedPixelEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.LedPixel = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(LedPixelReg.Brightness)
const [brightness] : [number] = brightnessReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const actualBrightnessReg = service.register(LedPixelReg.ActualBrightness)
actualBrightnessReg.on(REPORT_UPDATE, () => {

    
const [actualBrightness] : [number] = actualBrightnessReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "actualBrightness", actualBrightness.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const lightTypeReg = service.register(LedPixelReg.LightType)
const [lightType] : [jacdac.LedPixelLightType] = lightTypeReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const numPixelsReg = service.register(LedPixelReg.NumPixels)
const [numPixels] : [number] = numPixelsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const numColumnsReg = service.register(LedPixelReg.NumColumns)
const [numColumns] : [number] = numColumnsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxPowerReg = service.register(LedPixelReg.MaxPower)
const [maxPower] : [number] = maxPowerReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxPixelsReg = service.register(LedPixelReg.MaxPixels)
const [maxPixels] : [number] = maxPixelsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const numRepeatsReg = service.register(LedPixelReg.NumRepeats)
const [numRepeats] : [number] = numRepeatsReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(LedPixelReg.Variant)
const [variant] : [jacdac.LedPixelVariant] = variantReg.unpackedValue


}

 export {};