        
//AUTOGENERATED  by generator.ts
const {jacdac, LedReg, LedEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Led = function(service){

// get (register to REPORT_UPDATE event to enable background refresh)
const colorReg = service.register(LedReg.Color)
colorReg.on(REPORT_UPDATE, () => {

    
const [red, green, blue] : [number, number, number] = colorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "color", red.toString(),green.toString(),blue.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const maxPowerReg = service.register(LedReg.MaxPower)
const [maxPower] : [number] = maxPowerReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const ledCountReg = service.register(LedReg.LedCount)
const [ledCount] : [number] = ledCountReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const waveLengthReg = service.register(LedReg.WaveLength)
const [waveLength] : [number] = waveLengthReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const luminousIntensityReg = service.register(LedReg.LuminousIntensity)
const [luminousIntensity] : [number] = luminousIntensityReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(LedReg.Variant)
const [variant] : [jacdac.LedVariant] = variantReg.unpackedValue

}

 export {};