        
//AUTOGENERATED  by generator.ts
const {jacdac, LightLevelReg, LightLevelEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.LightLevel = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const lightLevelReg = service.register(LightLevelReg.LightLevel)
lightLevelReg.on(REPORT_UPDATE, () => {

    
const [lightLevel] : [number] = lightLevelReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "lightLevel", lightLevel.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const lightLevelErrorReg = service.register(LightLevelReg.LightLevelError)
lightLevelErrorReg.on(REPORT_UPDATE, () => {

    
const [lightLevelError] : [number] = lightLevelErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "lightLevelError", lightLevelError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(LightLevelReg.Variant)
const [variant] : [jacdac.LightLevelVariant] = variantReg.unpackedValue

}

 export {};