        
//AUTOGENERATED  by generator.ts
const {jacdac, LightBulbReg, LightBulbEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.LightBulb = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(LightBulbReg.Brightness)
const [brightness] : [number] = brightnessReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const dimmableReg = service.register(LightBulbReg.Dimmable)
const [dimmable] : [number] = dimmableReg.unpackedValue

}

 export {};