        
//AUTOGENERATED  by generator.ts
const {jacdac, LoggerReg, LoggerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Logger = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const minPriorityReg = service.register(LoggerReg.MinPriority)
const [minPriority] : [jacdac.LoggerPriority] = minPriorityReg.unpackedValue
// set









}

 export {};