        
//AUTOGENERATED  by generator.ts
const {jacdac, MagnetometerReg, MagnetometerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Magnetometer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const forcesReg = service.register(MagnetometerReg.Forces)
forcesReg.on(REPORT_UPDATE, () => {

    
const [x, y, z] : [number, number, number] = forcesReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "forces", x.toString(),y.toString(),z.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const forcesErrorReg = service.register(MagnetometerReg.ForcesError)
forcesErrorReg.on(REPORT_UPDATE, () => {

    
const [forcesError] : [number] = forcesErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "forcesError", forcesError.toString()])

})



}

 export {};