        
//AUTOGENERATED  by generator.ts
const {jacdac, MatrixKeypadReg, MatrixKeypadEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.MatrixKeypad = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const pressedReg = service.register(MatrixKeypadReg.Pressed)
pressedReg.on(REPORT_UPDATE, () => {

    
const [index] : [number[]] = pressedReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressed", index.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const rowsReg = service.register(MatrixKeypadReg.Rows)
const [rows] : [number] = rowsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const columnsReg = service.register(MatrixKeypadReg.Columns)
const [columns] : [number] = columnsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const labelsReg = service.register(MatrixKeypadReg.Labels)
const [label] : [string[]] = labelsReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(MatrixKeypadReg.Variant)
const [variant] : [jacdac.MatrixKeypadVariant] = variantReg.unpackedValue









}

 export {};