        
        //AUTOGENERATED  by generator.ts
        const {jacdac, MatrixKeypadReg, MatrixKeypadEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.MatrixKeypad = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const pressedReg = service.register(MatrixKeypadReg.Pressed)
pressedReg.on(REPORT_UPDATE, () => {

    
const [index] : [number[]] = pressedReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "pressed", index.toString()])

})










const downEvent = service.event(MatrixKeypadEvent.Down)
downEvent.on("change", () => {
    // if you need to read the event values
     const values = downEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_down", values.toString()])

})


const upEvent = service.event(MatrixKeypadEvent.Up)
upEvent.on("change", () => {
    // if you need to read the event values
     const values = upEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_up", values.toString()])

})


const clickEvent = service.event(MatrixKeypadEvent.Click)
clickEvent.on("change", () => {
    // if you need to read the event values
     const values = clickEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_click", values.toString()])

})


const longClickEvent = service.event(MatrixKeypadEvent.LongClick)
longClickEvent.on("change", () => {
    // if you need to read the event values
     const values = longClickEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_longClick", values.toString()])

})


}

 export {};