        
//AUTOGENERATED  by generator.ts
const {jacdac, MicrophoneReg, MicrophoneEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Microphone = function(service){

// get (register to REPORT_UPDATE event to enable background refresh)
const samplingPeriodReg = service.register(MicrophoneReg.SamplingPeriod)
const [samplingPeriod] : [number] = samplingPeriodReg.unpackedValue
// set

}

 export {};