        
//AUTOGENERATED  by generator.ts
const {jacdac, MidiOutputReg, MidiOutputEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.MidiOutput = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(MidiOutputReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set



}

 export {};