        
//AUTOGENERATED  by generator.ts
const {jacdac, ModelRunnerReg, ModelRunnerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.ModelRunner = function(service){






// get (register to REPORT_UPDATE event to enable background refresh)
const autoInvokeEveryReg = service.register(ModelRunnerReg.AutoInvokeEvery)
const [autoInvokeEvery] : [number] = autoInvokeEveryReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const outputsReg = service.register(ModelRunnerReg.Outputs)
outputsReg.on(REPORT_UPDATE, () => {

    
const [output] : [number[]] = outputsReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "outputs", output.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const inputShapeReg = service.register(ModelRunnerReg.InputShape)
inputShapeReg.on(REPORT_UPDATE, () => {

    
const [dimension] : [number[]] = inputShapeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "inputShape", dimension.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const outputShapeReg = service.register(ModelRunnerReg.OutputShape)
outputShapeReg.on(REPORT_UPDATE, () => {

    
const [dimension] : [number[]] = outputShapeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "outputShape", dimension.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const lastRunTimeReg = service.register(ModelRunnerReg.LastRunTime)
lastRunTimeReg.on(REPORT_UPDATE, () => {

    
const [lastRunTime] : [number] = lastRunTimeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "lastRunTime", lastRunTime.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const allocatedArenaSizeReg = service.register(ModelRunnerReg.AllocatedArenaSize)
allocatedArenaSizeReg.on(REPORT_UPDATE, () => {

    
const [allocatedArenaSize] : [number] = allocatedArenaSizeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "allocatedArenaSize", allocatedArenaSize.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const modelSizeReg = service.register(ModelRunnerReg.ModelSize)
modelSizeReg.on(REPORT_UPDATE, () => {

    
const [modelSize] : [number] = modelSizeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "modelSize", modelSize.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const lastErrorReg = service.register(ModelRunnerReg.LastError)
lastErrorReg.on(REPORT_UPDATE, () => {

    
const [lastError] : [string] = lastErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "lastError", lastError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const formatReg = service.register(ModelRunnerReg.Format)
const [format] : [jacdac.ModelRunnerModelFormat] = formatReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const formatVersionReg = service.register(ModelRunnerReg.FormatVersion)
const [formatVersion] : [number] = formatVersionReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const parallelReg = service.register(ModelRunnerReg.Parallel)
const [parallel] : [number] = parallelReg.unpackedValue

}

 export {};