        
        //AUTOGENERATED  by generator.ts
        const {jacdac, MotionReg, MotionEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Motion = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const movingReg = service.register(MotionReg.Moving)
movingReg.on(REPORT_UPDATE, () => {

    
const [moving] : [number] = movingReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "moving", moving.toString()])

})








const movementEvent = service.event(MotionEvent.Movement)
movementEvent.on("change", () => {
    // if you need to read the event values
     const values = movementEvent.unpackedValue
maxApi.outlet([service.maxID.toString(), "Event_movement", values.toString()])

})


}

 export {};