        
//AUTOGENERATED  by generator.ts
const {jacdac, MotionReg, MotionEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Motion = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const movingReg = service.register(MotionReg.Moving)
movingReg.on(REPORT_UPDATE, () => {

    
const [moving] : [number] = movingReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "moving", moving.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const maxDistanceReg = service.register(MotionReg.MaxDistance)
const [maxDistance] : [number] = maxDistanceReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const angleReg = service.register(MotionReg.Angle)
const [angle] : [number] = angleReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(MotionReg.Variant)
const [variant] : [jacdac.MotionVariant] = variantReg.unpackedValue



}

 export {};