        
//AUTOGENERATED  by generator.ts
const {jacdac, MotorReg, MotorEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Motor = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const dutyReg = service.register(MotorReg.Duty)
const [duty] : [number] = dutyReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(MotorReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const loadTorqueReg = service.register(MotorReg.LoadTorque)
const [loadTorque] : [number] = loadTorqueReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const loadSpeedReg = service.register(MotorReg.LoadSpeed)
const [loadSpeed] : [number] = loadSpeedReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const reversibleReg = service.register(MotorReg.Reversible)
const [reversible] : [number] = reversibleReg.unpackedValue

}

 export {};