        
        //AUTOGENERATED  by generator.ts
        const {jacdac, PotentiometerReg, PotentiometerEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.Potentiometer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const positionReg = service.register(PotentiometerReg.Position)
positionReg.on(REPORT_UPDATE, () => {

    
const [position] : [number] = positionReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "position", position.toString()])

})




}

 export {};