        
//AUTOGENERATED  by generator.ts
const {jacdac, PowerReg, PowerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Power = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const allowedReg = service.register(PowerReg.Allowed)
const [allowed] : [number] = allowedReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxPowerReg = service.register(PowerReg.MaxPower)
const [maxPower] : [number] = maxPowerReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const powerStatusReg = service.register(PowerReg.PowerStatus)
powerStatusReg.on(REPORT_UPDATE, () => {

    
const [powerStatus] : [jacdac.PowerPowerStatus] = powerStatusReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "powerStatus", powerStatus.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const currentDrawReg = service.register(PowerReg.CurrentDraw)
currentDrawReg.on(REPORT_UPDATE, () => {

    
const [currentDraw] : [number] = currentDrawReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "currentDraw", currentDraw.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const batteryVoltageReg = service.register(PowerReg.BatteryVoltage)
batteryVoltageReg.on(REPORT_UPDATE, () => {

    
const [batteryVoltage] : [number] = batteryVoltageReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "batteryVoltage", batteryVoltage.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const batteryChargeReg = service.register(PowerReg.BatteryCharge)
batteryChargeReg.on(REPORT_UPDATE, () => {

    
const [batteryCharge] : [number] = batteryChargeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "batteryCharge", batteryCharge.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const batteryCapacityReg = service.register(PowerReg.BatteryCapacity)
const [batteryCapacity] : [number] = batteryCapacityReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const keepOnPulseDurationReg = service.register(PowerReg.KeepOnPulseDuration)
const [keepOnPulseDuration] : [number] = keepOnPulseDurationReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const keepOnPulsePeriodReg = service.register(PowerReg.KeepOnPulsePeriod)
const [keepOnPulsePeriod] : [number] = keepOnPulsePeriodReg.unpackedValue
// set




}

 export {};