        
//AUTOGENERATED  by generator.ts
const {jacdac, PressureButtonReg, PressureButtonEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.PressureButton = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const thresholdReg = service.register(PressureButtonReg.Threshold)
const [threshold] : [number] = thresholdReg.unpackedValue
// set

}

 export {};