        
//AUTOGENERATED  by generator.ts
const {jacdac, ProxyReg, ProxyEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Proxy = function(service){


}

 export {};