        
        //AUTOGENERATED  by generator.ts
        const {jacdac, PulseOximeterReg, PulseOximeterEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.PulseOximeter = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const oxygenReg = service.register(PulseOximeterReg.Oxygen)
oxygenReg.on(REPORT_UPDATE, () => {

    
const [oxygen] : [number] = oxygenReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "oxygen", oxygen.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const oxygenErrorReg = service.register(PulseOximeterReg.OxygenError)
oxygenErrorReg.on(REPORT_UPDATE, () => {

    
const [oxygenError] : [number] = oxygenErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "oxygenError", oxygenError.toString()])

})


}

 export {};