        
        //AUTOGENERATED  by generator.ts
        const {jacdac, RainGaugeReg, RainGaugeEvent,  REPORT_UPDATE} = require("jacdac-ts")
        const maxApi = require("max-api")
        
        exports.RainGauge = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const precipitationReg = service.register(RainGaugeReg.Precipitation)
precipitationReg.on(REPORT_UPDATE, () => {

    
const [precipitation] : [number] = precipitationReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "precipitation", precipitation.toString()])

})




}

 export {};