        
//AUTOGENERATED  by generator.ts
const {jacdac, RngReg, RngEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Rng = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const randomReg = service.register(RngReg.Random)
randomReg.on(REPORT_UPDATE, () => {

    
const [random] : [Buffer] = randomReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "random", random.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(RngReg.Variant)
const [variant] : [jacdac.RngVariant] = variantReg.unpackedValue

}

 export {};