        
//AUTOGENERATED  by generator.ts
const {jacdac, RealTimeClockReg, RealTimeClockEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.RealTimeClock = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const localTimeReg = service.register(RealTimeClockReg.LocalTime)
localTimeReg.on(REPORT_UPDATE, () => {

    
const [year, month, dayOfMonth, dayOfWeek, hour, min, sec] : [number, number, number, number, number, number, number] = localTimeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "localTime", year.toString(),month.toString(),dayOfMonth.toString(),dayOfWeek.toString(),hour.toString(),min.toString(),sec.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const driftReg = service.register(RealTimeClockReg.Drift)
driftReg.on(REPORT_UPDATE, () => {

    
const [drift] : [number] = driftReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "drift", drift.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const precisionReg = service.register(RealTimeClockReg.Precision)
const [precision] : [number] = precisionReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(RealTimeClockReg.Variant)
const [variant] : [jacdac.RealTimeClockVariant] = variantReg.unpackedValue


}

 export {};