        
//AUTOGENERATED  by generator.ts
const {jacdac, ReflectedLightReg, ReflectedLightEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.ReflectedLight = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const brightnessReg = service.register(ReflectedLightReg.Brightness)
brightnessReg.on(REPORT_UPDATE, () => {

    
const [brightness] : [number] = brightnessReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "brightness", brightness.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(ReflectedLightReg.Variant)
const [variant] : [jacdac.ReflectedLightVariant] = variantReg.unpackedValue

}

 export {};