        
//AUTOGENERATED  by generator.ts
const {jacdac, RelayReg, RelayEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Relay = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const closedReg = service.register(RelayReg.Closed)
const [closed] : [number] = closedReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(RelayReg.Variant)
const [variant] : [jacdac.RelayVariant] = variantReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxSwitchingCurrentReg = service.register(RelayReg.MaxSwitchingCurrent)
const [maxSwitchingCurrent] : [number] = maxSwitchingCurrentReg.unpackedValue

}

 export {};