        
//AUTOGENERATED  by generator.ts
const {jacdac, RoleManagerReg, RoleManagerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.RoleManager = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const autoBindReg = service.register(RoleManagerReg.AutoBind)
const [autoBind] : [number] = autoBindReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const allRolesAllocatedReg = service.register(RoleManagerReg.AllRolesAllocated)
allRolesAllocatedReg.on(REPORT_UPDATE, () => {

    
const [allRolesAllocated] : [number] = allRolesAllocatedReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "allRolesAllocated", allRolesAllocated.toString()])

})















}

 export {};