        
//AUTOGENERATED  by generator.ts
const {jacdac, RoverReg, RoverEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Rover = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const kinematicsReg = service.register(RoverReg.Kinematics)
kinematicsReg.on(REPORT_UPDATE, () => {

    
const [x, y, vx, vy, heading] : [number, number, number, number, number] = kinematicsReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "kinematics", x.toString(),y.toString(),vx.toString(),vy.toString(),heading.toString()])

})


}

 export {};