        
//AUTOGENERATED  by generator.ts
const {jacdac, SensorAggregatorReg, SensorAggregatorEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.SensorAggregator = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const inputsReg = service.register(SensorAggregatorReg.Inputs)
const [samplingInterval, samplesInWindow, rest] : [number, number, ([Buffer, number, number, number, jacdac.SensorAggregatorSampleType, number])[]] = inputsReg.unpackedValue
// set
const [deviceId, serviceClass, serviceNum, sampleSize, sampleType, sampleShift] = rest[0]

// get (register to REPORT_UPDATE event to enable background refresh)
const numSamplesReg = service.register(SensorAggregatorReg.NumSamples)
numSamplesReg.on(REPORT_UPDATE, () => {

    
const [numSamples] : [number] = numSamplesReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "numSamples", numSamples.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const sampleSizeReg = service.register(SensorAggregatorReg.SampleSize)
sampleSizeReg.on(REPORT_UPDATE, () => {

    
const [sampleSize] : [number] = sampleSizeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "sampleSize", sampleSize.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const streamingSamplesReg = service.register(SensorAggregatorReg.StreamingSamples)
const [streamingSamples] : [number] = streamingSamplesReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const currentSampleReg = service.register(SensorAggregatorReg.CurrentSample)
currentSampleReg.on(REPORT_UPDATE, () => {

    
const [currentSample] : [Buffer] = currentSampleReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "currentSample", currentSample.toString()])

})


}

 export {};