        
//AUTOGENERATED  by generator.ts
const {jacdac, SensorReg, SensorEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Sensor = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const streamingSamplesReg = service.register(SensorReg.StreamingSamples)
const [streamingSamples] : [number] = streamingSamplesReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const streamingIntervalReg = service.register(SensorReg.StreamingInterval)
const [streamingInterval] : [number] = streamingIntervalReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const streamingPreferredIntervalReg = service.register(SensorReg.StreamingPreferredInterval)
const [streamingPreferredInterval] : [number] = streamingPreferredIntervalReg.unpackedValue

}

 export {};