        
//AUTOGENERATED  by generator.ts
const {jacdac, ServoReg, ServoEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Servo = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const angleReg = service.register(ServoReg.Angle)
const [angle] : [number] = angleReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(ServoReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const offsetReg = service.register(ServoReg.Offset)
const [offset] : [number] = offsetReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const minAngleReg = service.register(ServoReg.MinAngle)
const [minAngle] : [number] = minAngleReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const minPulseReg = service.register(ServoReg.MinPulse)
const [minPulse] : [number] = minPulseReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxAngleReg = service.register(ServoReg.MaxAngle)
const [maxAngle] : [number] = maxAngleReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const maxPulseReg = service.register(ServoReg.MaxPulse)
const [maxPulse] : [number] = maxPulseReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const stallTorqueReg = service.register(ServoReg.StallTorque)
const [stallTorque] : [number] = stallTorqueReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const responseSpeedReg = service.register(ServoReg.ResponseSpeed)
const [responseSpeed] : [number] = responseSpeedReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const currentAngleReg = service.register(ServoReg.CurrentAngle)
currentAngleReg.on(REPORT_UPDATE, () => {

    
const [currentAngle] : [number] = currentAngleReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "currentAngle", currentAngle.toString()])

})


}

 export {};