        
//AUTOGENERATED  by generator.ts
const {jacdac, SettingsReg, SettingsEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Settings = function(service){














}

 export {};