        
//AUTOGENERATED  by generator.ts
const {jacdac, SoilMoistureReg, SoilMoistureEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.SoilMoisture = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const moistureReg = service.register(SoilMoistureReg.Moisture)
moistureReg.on(REPORT_UPDATE, () => {

    
const [moisture] : [number] = moistureReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "moisture", moisture.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const moistureErrorReg = service.register(SoilMoistureReg.MoistureError)
moistureErrorReg.on(REPORT_UPDATE, () => {

    
const [moistureError] : [number] = moistureErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "moistureError", moistureError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(SoilMoistureReg.Variant)
const [variant] : [jacdac.SoilMoistureVariant] = variantReg.unpackedValue

}

 export {};