        
//AUTOGENERATED  by generator.ts
const {jacdac, SolenoidReg, SolenoidEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Solenoid = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const pulledReg = service.register(SolenoidReg.Pulled)
const [pulled] : [number] = pulledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(SolenoidReg.Variant)
const [variant] : [jacdac.SolenoidVariant] = variantReg.unpackedValue

}

 export {};