        
//AUTOGENERATED  by generator.ts
const {jacdac, SoundPlayerReg, SoundPlayerEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.SoundPlayer = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const volumeReg = service.register(SoundPlayerReg.Volume)
const [volume] : [number] = volumeReg.unpackedValue
// set






}

 export {};