        
//AUTOGENERATED  by generator.ts
const {jacdac, SwitchReg, SwitchEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Switch = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const activeReg = service.register(SwitchReg.Active)
activeReg.on(REPORT_UPDATE, () => {

    
const [active] : [number] = activeReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "active", active.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(SwitchReg.Variant)
const [variant] : [jacdac.SwitchVariant] = variantReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const autoOffDelayReg = service.register(SwitchReg.AutoOffDelay)
const [autoOffDelay] : [number] = autoOffDelayReg.unpackedValue





}

 export {};