        
//AUTOGENERATED  by generator.ts
const {jacdac, TcpReg, TcpEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Tcp = function(service){











}

 export {};