        
//AUTOGENERATED  by generator.ts
const {jacdac, TrafficLightReg, TrafficLightEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.TrafficLight = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const redReg = service.register(TrafficLightReg.Red)
const [red] : [number] = redReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const orangeReg = service.register(TrafficLightReg.Orange)
const [orange] : [number] = orangeReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const greenReg = service.register(TrafficLightReg.Green)
const [green] : [number] = greenReg.unpackedValue
// set

}

 export {};