        
//AUTOGENERATED  by generator.ts
const {jacdac, UniqueBrainReg, UniqueBrainEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.UniqueBrain = function(service){


}

 export {};