        
//AUTOGENERATED  by generator.ts
const {jacdac, VerifiedTelemetryReg, VerifiedTelemetryEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.VerifiedTelemetry = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const telemetryStatusReg = service.register(VerifiedTelemetryReg.TelemetryStatus)
telemetryStatusReg.on(REPORT_UPDATE, () => {

    
const [telemetryStatus] : [jacdac.VerifiedTelemetryStatus] = telemetryStatusReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "telemetryStatus", telemetryStatus.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const telemetryStatusIntervalReg = service.register(VerifiedTelemetryReg.TelemetryStatusInterval)
const [telemetryStatusInterval] : [number] = telemetryStatusIntervalReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const fingerprintTypeReg = service.register(VerifiedTelemetryReg.FingerprintType)
const [fingerprintType] : [jacdac.VerifiedTelemetryFingerprintType] = fingerprintTypeReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const fingerprintTemplateReg = service.register(VerifiedTelemetryReg.FingerprintTemplate)
fingerprintTemplateReg.on(REPORT_UPDATE, () => {

    
const [confidence, template] : [number, Buffer] = fingerprintTemplateReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "fingerprintTemplate", confidence.toString(),template.toString()])

})








}

 export {};