        
//AUTOGENERATED  by generator.ts
const {jacdac, VibrationMotorReg, VibrationMotorEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.VibrationMotor = function(service){
const [duration, intensity] = rest[0]

}

 export {};