        
//AUTOGENERATED  by generator.ts
const {jacdac, WeightScaleReg, WeightScaleEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.WeightScale = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const weightReg = service.register(WeightScaleReg.Weight)
weightReg.on(REPORT_UPDATE, () => {

    
const [weight] : [number] = weightReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "weight", weight.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const weightErrorReg = service.register(WeightScaleReg.WeightError)
weightErrorReg.on(REPORT_UPDATE, () => {

    
const [weightError] : [number] = weightErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "weightError", weightError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const zeroOffsetReg = service.register(WeightScaleReg.ZeroOffset)
const [zeroOffset] : [number] = zeroOffsetReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const gainReg = service.register(WeightScaleReg.Gain)
const [gain] : [number] = gainReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const maxWeightReg = service.register(WeightScaleReg.MaxWeight)
const [maxWeight] : [number] = maxWeightReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const minWeightReg = service.register(WeightScaleReg.MinWeight)
const [minWeight] : [number] = minWeightReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const weightResolutionReg = service.register(WeightScaleReg.WeightResolution)
const [weightResolution] : [number] = weightResolutionReg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const variantReg = service.register(WeightScaleReg.Variant)
const [variant] : [jacdac.WeightScaleVariant] = variantReg.unpackedValue



}

 export {};