        
//AUTOGENERATED  by generator.ts
const {jacdac, WifiReg, WifiEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.Wifi = function(service){












// get (register to REPORT_UPDATE event to enable background refresh)
const enabledReg = service.register(WifiReg.Enabled)
const [enabled] : [number] = enabledReg.unpackedValue
// set

// get (register to REPORT_UPDATE event to enable background refresh)
const ipAddressReg = service.register(WifiReg.IpAddress)
ipAddressReg.on(REPORT_UPDATE, () => {

    
const [ipAddress] : [Buffer] = ipAddressReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "ipAddress", ipAddress.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const eui48Reg = service.register(WifiReg.Eui48)
const [eui48] : [Buffer] = eui48Reg.unpackedValue

// get (register to REPORT_UPDATE event to enable background refresh)
const ssidReg = service.register(WifiReg.Ssid)
ssidReg.on(REPORT_UPDATE, () => {

    
const [ssid] : [string] = ssidReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "ssid", ssid.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const rssiReg = service.register(WifiReg.Rssi)
rssiReg.on(REPORT_UPDATE, () => {

    
const [rssi] : [number] = rssiReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "rssi", rssi.toString()])

})












}

 export {};