        
//AUTOGENERATED  by generator.ts
const {jacdac, WindSpeedReg, WindSpeedEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.WindSpeed = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const windSpeedReg = service.register(WindSpeedReg.WindSpeed)
windSpeedReg.on(REPORT_UPDATE, () => {

    
const [windSpeed] : [number] = windSpeedReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "windSpeed", windSpeed.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const windSpeedErrorReg = service.register(WindSpeedReg.WindSpeedError)
windSpeedErrorReg.on(REPORT_UPDATE, () => {

    
const [windSpeedError] : [number] = windSpeedErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "windSpeedError", windSpeedError.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const maxWindSpeedReg = service.register(WindSpeedReg.MaxWindSpeed)
const [maxWindSpeed] : [number] = maxWindSpeedReg.unpackedValue

}

 export {};