        
//AUTOGENERATED  by generator.ts
const {jacdac, WindDirectionReg, WindDirectionEvent, REPORT_UPDATE} = require("jacdac-ts")
const maxApi = require("max-api")

exports.WindDirection = function(service){
// get (register to REPORT_UPDATE event to enable background refresh)
const windDirectionReg = service.register(WindDirectionReg.WindDirection)
windDirectionReg.on(REPORT_UPDATE, () => {

    
const [windDirection] : [number] = windDirectionReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "windDirection", windDirection.toString()])

})


// get (register to REPORT_UPDATE event to enable background refresh)
const windDirectionErrorReg = service.register(WindDirectionReg.WindDirectionError)
windDirectionErrorReg.on(REPORT_UPDATE, () => {

    
const [windDirectionError] : [number] = windDirectionErrorReg.unpackedValue
maxApi.outlet([service.maxID.toString(), "windDirectionError", windDirectionError.toString()])

})


}

 export {};